### ISSUE TITLE
Deep/nested object changes not detected

### ISSUE THREAD

**Issue by imperatormk** [sergiofasilva/object-state-history#11]
Hey please check:

`const ObjectStateHistory = require('object-state-history')

const obj = {
  num: 1,
  str: "2",
  bool: false,
  arr: [3, "4", true],
  nobj: {
    nnum: 5,
    narr: [6, "7", { nbool: true }]
  }
};

const diff = new ObjectStateHistory(obj)

diff.nobj.narr[0] = 60 // doesn't work!
diff.nobj.nnum = 50; // doesn't work!
diff.merge({ nobj: { nnum: 55 } }) // overwrites .nobj.narr

console.warn(diff.list())`

Is this already known/intentional?

**Comment by sergiofasilva** [comment]
> Hey please check:
> 
> `const ObjectStateHistory = require('object-state-history')
> 
> const obj = { num: 1, str: "2", bool: false, arr: [3, "4", true], nobj: { nnum: 5, narr: [6, "7", { nbool: true }] } };
> 
> const diff = new ObjectStateHistory(obj)
> 
> diff.nobj.narr[0] = 60 // doesn't work! diff.nobj.nnum = 50; // doesn't work! diff.merge({ nobj: { nnum: 55 } }) // overwrites .nobj.narr
> 
> console.warn(diff.list())`
> 
> Is this already known/intentional?

@imperatormk, thank you for your comment.

This situation is well known. I thought I had documented it, but it turns out I hadn't.
There are various technical reasons for this.

I'll have to update the documentation with that information.
